# Generated by Django 6.0 on 2025-12-31 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('tc_no', models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN')),
                ('banka_adi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Banka Adı')),
                ('calisma_tipi', models.CharField(choices=[('aylik', 'Aylık Maaşlı'), ('gunluk', 'Günlük Yevmiyeli')], default='aylik', max_length=10, verbose_name='Çalışma Tipi')),
                ('maas_tutari', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maaş/Yevmiye Tutarı')),
                ('ozel_mesai_ucreti', models.DecimalField(decimal_places=2, default=250.0, max_digits=10, verbose_name='Saatlik Mesai Ücreti')),
                ('gunluk_calisma_saati', models.PositiveIntegerField(default=8, verbose_name='Günlük Çalışma Saati (Saat)')),
                ('ise_giris_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='İşe Giriş Tarihi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif Personel')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
            },
        ),
        migrations.CreateModel(
            name='FinansalHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('islem_tipi', models.CharField(choices=[('basit_avans', 'Basit Avans (Elden)'), ('kasa_acigi', 'Kasa Açığı'), ('alisveris', 'Alışveriş/Yeme-İçme'), ('prim', 'Prim (Maaşa Ek)')], max_length=20, verbose_name='İşlem Tipi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('aciklama', models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finansal_hareketler', to='core.personel')),
            ],
            options={
                'verbose_name': 'Finansal Hareket (Avans/Kesinti)',
                'verbose_name_plural': 'Finansal Hareketler',
            },
        ),
        migrations.CreateModel(
            name='TaksitliAvans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Veriliş Tarihi')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar')),
                ('taksit_sayisi', models.PositiveIntegerField(default=1, verbose_name='Taksit Sayısı')),
                ('aylik_kesinti', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Aylık Kesilecek Tutar')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('tamamlandi', models.BooleanField(default=False, verbose_name='Borç Bitti mi?')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taksitli_avanslar', to='core.personel')),
            ],
            options={
                'verbose_name': 'Taksitli Avans',
                'verbose_name_plural': 'Taksitli Avanslar',
            },
        ),
        migrations.CreateModel(
            name='Puantaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('durum', models.CharField(choices=[('geldi', 'Geldi'), ('gelmedi', 'Gelmedi'), ('izinli', 'İzinli (Ücretli)'), ('ucretsiz_izin', 'Ücretsiz İzin'), ('raporlu', 'Raporlu')], default='geldi', max_length=20, verbose_name='Durum')),
                ('giris_saati', models.TimeField(blank=True, null=True, verbose_name='Giriş Saati')),
                ('cikis_saati', models.TimeField(blank=True, null=True, verbose_name='Çıkış Saati')),
                ('hesaplanan_mesai_saati', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Hesaplanan Mesai (Saat)')),
                ('manuel_mesai_saati', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Manuel Düzeltme (Varsa)')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puantajlar', to='core.personel')),
            ],
            options={
                'verbose_name': 'Günlük Yoklama',
                'verbose_name_plural': 'Günlük Yoklamalar',
                'unique_together': {('personel', 'tarih')},
            },
        ),
    ]
