# Generated by Django 6.0 on 2025-12-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finansalhareket',
            options={'verbose_name': 'Finansal Hareket (Avans/Prim)', 'verbose_name_plural': 'Finansal Hareketler'},
        ),
        migrations.AlterField(
            model_name='finansalhareket',
            name='islem_tipi',
            field=models.CharField(choices=[('basit_avans', 'Basit Avans (Kesinti)'), ('kasa_acigi', 'Kasa Açığı (Kesinti)'), ('alisveris', 'Alışveriş/Yeme-İçme (Kesinti)'), ('prim', 'Prim / Bonus (MAAŞA EKLENİR)')], max_length=20, verbose_name='İşlem Tipi'),
        ),
        migrations.AlterField(
            model_name='puantaj',
            name='durum',
            field=models.CharField(choices=[('geldi', 'Geldi (Normal)'), ('hafta_tatili', 'Hafta Tatili Çalışması (Tüm Saatler Mesai)'), ('gelmedi', 'Gelmedi'), ('izinli', 'İzinli (Ücretli)'), ('ucretsiz_izin', 'Ücretsiz İzin'), ('raporlu', 'Raporlu')], default='geldi', max_length=20, verbose_name='Durum'),
        ),
    ]
