"""
Django settings for avlu_backend project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os
import environ # django-environ kütüphanesi

# 1. Env başlatma
env = environ.Env(
    # Varsayılan değerler (Localde env dosyası yoksa veya değişken yoksa bunları kullanır)
    DEBUG=(bool, True),
    SECRET_KEY=(str, 'django-insecure-change-me-locally'),
    DATABASE_URL=(str, 'sqlite:///db.sqlite3')
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env dosyasını oku (Eğer varsa)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = env('SECRET_KEY')

# Google Cloud'da bu değer False olmalı, env dosyasından veya Cloud ayarlarından gelir
DEBUG = env('DEBUG')

# Cloud Run domaini veya '*' (tüm hostlar)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])

# Güvenlik için CSRF ayarları (HTTPS üzerinden çalışacağımız için gerekli)
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=['https://*.run.app'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic', # Geliştirme ortamında whitenoise kullanımı
    'django.contrib.staticfiles',
    'core',  # Sizin uygulamanız
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <-- CSS/JS sunumu için EKLENDİ (En üste yakın olmalı)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'avlu_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'avlu_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Veritabanı ayarı artık dinamik.
# Localde: sqlite:///db.sqlite3
# Cloud'da: postgres://kullanici:sifre@host:port/db_adi formatında env değişkeni gelecek.
DATABASES = {
    'default': env.db()
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Collectstatic komutu buraya toplar

# Whitenoise Ayarları (Production'da static dosyaları sıkıştırıp sunar)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# --- GÜVENLİK VE GİRİŞ YÖNLENDİRMELERİ ---

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'ana_sayfa'
LOGOUT_REDIRECT_URL = 'login'

# --- E-POSTA AYARLARI (Yedekleme İçin) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_PASSWORD', default='')